### ISSUE TITLE
Expiry date on images from google storage affects rss readers

### ISSUE THREAD

**Issue by SamuelmdLow** [ubyssey/ubyssey-dispatch-theme#1275]
When we retrieve an image from the google storage it has an expiry date added to the url. When rss readers save the feed to their own database they get this expiry date. If it hasn't parsed the feed in a while then all the images will be past the expiry date. Items no longer listed but saved by the rss reader will also have images past the expiry date.

**Comment by SamuelmdLow** [comment]
@psiemens

**Comment by psiemens** [comment]
Those URLs you are seeing are [signed URLs](https://cloud.google.com/storage/docs/access-control/signed-urls), which are typically used to give limited access to non-public files. They're dynamically generated on each page load but then expire after a period of time (likely a few minutes max). However, all static files on the site (including images) should be publicly viewable by default, so we shouldn't need to use signed URLs. Currently the site is returning signed URLs for all files but it's probably most noticeable when using an RSS reader or other service that retain references to Ubyssey files.

At first I thought this happening was because the`GS_USE_SIGNED_URLS` flag is [enabled](https://github.com/ubyssey/ubyssey.ca/blob/develop/config/settings/production.py#L50), but it looks like that's an obsolete setting for Dispatch. That line can be deleted.

According to the [Django Storages documentation](https://django-storages.readthedocs.io/en/latest/backends/gcloud.html#settings), the `GS_QUERYSTRING_AUTH = False` line _should_ force the site not to use signed URLs, but I think our version of `django-storages` (v1.10) doesn't actually accept that flag. Upgrading to v1.11 or newer should fix that.

I'd recommend that we take these steps:
- Check that the GCS bucket permissions allow [uniform public read access](https://cloud.google.com/storage/docs/access-control) to static files (and ensure that no private files are stored there)
- Remove the `GS_USE_SIGNED_URLS` setting since it is no longer needed
- Upgrade `django-storages` to the latest version (or at least v1.11). This can be done in [requirements.txt](https://github.com/ubyssey/ubyssey.ca/blob/develop/requirements.txt#L4)
