### ISSUE TITLE
Magazine: design landing page

### ISSUE THREAD

**Issue by psiemens** [ubyssey/ubyssey-dispatch-theme#188]
Here's a _very_ rough idea of what I'm thinking for the landing page.

The idea here is that there'd be one cover article, a few featured articles, and then the rest would be tiled down the page.

@ubyssey/magazine Let me know what you think!

![img_8969](https://cloud.githubusercontent.com/assets/2547035/22482348/7db1a076-e7ad-11e6-8ead-4b1a81e0f064.JPG)

**Comment by floriecai** [comment]
Landing page: Tiles around the cover article. The image isn't draw to scale well but the top row of tiles would be shorter in height compared to the cover article. 

![img_20170202_121308](https://cloud.githubusercontent.com/assets/8770192/22620569/7e98b97a-eac3-11e6-826f-1bbb2a207fb3.jpg)

Possible template for articles? I think it'd be nice to have some consistent header/footer and some bold borders to give it more a "magazine feel" rather than the same Ubyssey newspaper look. 

![img_20170204_100137](https://cloud.githubusercontent.com/assets/8770192/22620570/8275a134-eac3-11e6-9ca2-98dbc16432b6.jpg)

Let me know what everyone's thinking! @ubyssey/magazine

**Comment by floriecai** [comment]
The first one is the landing page and the second is a possible template for the article. I think it'd be nice to have some consistent header/footer (doesn't have to be the ones what I drew). Something that gives it more a "magazine" feel instead of just the Ubyssey newspaper one. Let me know what you guys think @ubyssey/magazine

**Comment by sherryinx** [comment]
[landing page mockup.pdf](https://github.com/ubyssey/ubyssey-dispatch-theme/files/752580/landing.page.mockup.pdf)

**Invision Prototype:** 
https://invis.io/2BABGDY6N#/217496636_Desktop

Please let me know if you guys have suggestions for the layout and colours! I'll be updating the Invision link as we go.

**Comment by ghost** [comment]
[landing page mockup.pdf](https://github.com/ubyssey/ubyssey-dispatch-theme/files/752589/landing.page.mockup.pdf)

Invision Prototype:
https://invis.io/2BABGDY6N#/217496636_Desktop

Please let me know if you guys have suggestions for the layout and colours! I'll be updating the Invision link as we go.
