### ISSUE TITLE
Home page top articles featured/pinned articles

### ISSUE THREAD

**Issue by ihciem** [ubyssey/ubyssey-dispatch-theme#971]
Establish priority of articles on homepage.

- articles could be published and not replace what is **"pinned"** to the homepage of the website.
- new articles could be displayed off to the side on the homepage

**Comment by ihciem** [comment]
Use 'order_by'?

https://stackoverflow.com/questions/66570706/how-to-pin-posts-in-django

**Comment by keeganland** [comment]
somewhat a NTS: I've been thinking about the "pinning" idea we've been tossing around and the big problem I foresee with most ways to do it is if pins end up being listed separately from nonpin articles we risk getting redundancies when selecting things to display. Article Mei posted is particularly useful because it gets around this issue

**Comment by FireBoyAJ24** [comment]
There is a breaking news banner that in a sense replicates the idea of a featured/pinned article. The PR is #512.
The breaking article that is 2 hours old since being published is placed on the front page. The breaking news article will only show the link to the article.

We need to re-evaluate the purpose of a pinned article and check fully whether the breaking banner is fully operational.

**Comment by SamuelmdLow** [comment]
This is accomplished in the redesign
